### ISSUE TITLE
php don't run

### ISSUE THREAD

**Issue by zoneprog** [timonier/php#1]
`ERROR: failed to open configuration file '/run/php/etc/php-fpm.conf': No such file or directory (2)
ERROR: failed to load configuration file '/run/php/etc/php-fpm.conf'
ERROR: FPM initialization failed
`

**Comment by mauchede** [comment]
Hello @zoneprog,

Oops, I did not know that this image was used by someone else. I will revert my last changes.

Can you just put a "star" on this project (and do the same for each timonier projects used)? It will show who is using the project and when I have to apply a better BC politicy.

**Comment by mauchede** [comment]
It should be OK now (images have been rebuilt).

**Comment by zoneprog** [comment]
Hello @mauchede 

it's good now, thanks.

I added the star
